//! Golden-vector wire-format tests.
//!
//! The fixture `golden_vectors_v0.txt` was generated by the pre-modernization
//! codebase (arkworks 0.4 / bincode 1 era). These tests pin three invariants:
//! artifacts serialized by old code still parse and re-serialize
//! byte-identically, deterministic key derivation from fixed randomness is
//! stable, and old ciphertexts still decrypt. If a change breaks one of these,
//! it breaks compatibility with every artifact persisted by earlier builds —
//! do not regenerate the fixture to make the test pass without treating the
//! change as a wire-format break.

use std::{collections::HashMap, str::FromStr};

use ferveo::{
    api::{
        combine_shares_simple, decrypt_with_shared_secret,
        AggregatedTranscript, Ciphertext, Dkg, Transcript, Validator,
        ValidatorKeypair, ValidatorMessage,
    },
    EthereumAddress,
};
use ferveo_common::serialization::{FromBytes, ToBytes};
use sha2::{Digest, Sha256};

const FIXTURE: &str = include_str!("golden_vectors_v0.txt");
const TAU: u32 = 0;
const SHARES_NUM: u32 = 4;
const THRESHOLD: u32 = 3;
const MSG: &[u8] = b"ferveo-golden-msg";
const AAD: &[u8] = b"ferveo-golden-aad";
const KEYPAIR_SEED: [u8; 32] = [7u8; 32];

fn vectors() -> HashMap<String, Vec<u8>> {
    FIXTURE
        .lines()
        .filter(|l| l.contains('='))
        .map(|l| {
            let (k, v) = l.split_once('=').unwrap();
            (k.to_string(), hex::decode(v.trim()).unwrap())
        })
        .collect()
}

fn get(vectors: &HashMap<String, Vec<u8>>, key: &str) -> Vec<u8> {
    vectors
        .get(key)
        .unwrap_or_else(|| panic!("missing vector {key}"))
        .clone()
}

fn roundtrip<T: ToBytes + FromBytes>(name: &str, bytes: &[u8]) -> T {
    let value = T::from_bytes(bytes)
        .unwrap_or_else(|e| panic!("{name}: old-format read failed: {e}"));
    assert_eq!(
        value.to_bytes().unwrap(),
        bytes,
        "{name}: re-serialization not byte-identical (wire format changed)"
    );
    value
}

fn make_validators(keypairs: &[ValidatorKeypair]) -> Vec<Validator> {
    keypairs
        .iter()
        .enumerate()
        .map(|(i, kp)| Validator {
            address: EthereumAddress::from_str(&format!("0x{i:040}")).unwrap(),
            public_key: kp.public_key(),
            share_index: i as u32,
        })
        .collect()
}

#[test]
fn seeded_key_derivation_is_stable() {
    let vectors = vectors();
    let seeded =
        ValidatorKeypair::from_secure_randomness(&KEYPAIR_SEED).unwrap();
    assert_eq!(
        seeded.public_key().to_bytes().unwrap().to_vec(),
        get(&vectors, "seeded_keypair_pubkey"),
        "seeded key derivation changed (rng stream or serialization)"
    );
}

#[test]
fn old_artifacts_roundtrip_and_decrypt() {
    let vectors = vectors();

    let keypairs: Vec<ValidatorKeypair> = (0..SHARES_NUM)
        .map(|i| {
            roundtrip(
                &format!("validator_keypair_{i}"),
                &get(&vectors, &format!("validator_keypair_{i}")),
            )
        })
        .collect();
    let transcripts: Vec<Transcript> = (0..SHARES_NUM)
        .map(|i| {
            roundtrip(
                &format!("transcript_{i}"),
                &get(&vectors, &format!("transcript_{i}")),
            )
        })
        .collect();
    let stored_agg: AggregatedTranscript =
        roundtrip("agg_transcript", &get(&vectors, "agg_transcript"));
    let ciphertext: Ciphertext =
        roundtrip("ciphertext", &get(&vectors, "ciphertext"));

    let validators = make_validators(&keypairs);
    let messages: Vec<ValidatorMessage> = validators
        .iter()
        .cloned()
        .zip(transcripts.iter().cloned())
        .collect();
    let dkg = Dkg::new(TAU, SHARES_NUM, THRESHOLD, &validators, &validators[0])
        .unwrap();
    let agg = dkg
        .aggregate_transcripts(&messages)
        .expect("aggregation of old transcripts failed");
    assert!(
        agg.verify(SHARES_NUM, &messages).unwrap(),
        "old transcripts no longer verify"
    );
    assert_eq!(
        agg.to_bytes().unwrap(),
        stored_agg.to_bytes().unwrap(),
        "re-aggregation differs from stored aggregate"
    );
    assert_eq!(
        agg.public_key().to_bytes().unwrap().to_vec(),
        get(&vectors, "dkg_public_key"),
        "DKG public key changed"
    );

    let header = ciphertext.header().unwrap();
    let shares: Vec<_> = (0..THRESHOLD as usize)
        .map(|i| {
            let dkg_i = Dkg::new(
                TAU,
                SHARES_NUM,
                THRESHOLD,
                &validators,
                &validators[i],
            )
            .unwrap();
            agg.create_decryption_share_simple(
                &dkg_i,
                &header,
                AAD,
                &keypairs[i],
            )
            .unwrap()
        })
        .collect();
    let shared_secret = combine_shares_simple(&shares);
    assert_eq!(
        hex::encode(Sha256::digest(shared_secret.to_bytes().unwrap())),
        hex::encode(get(&vectors, "shared_secret_sha256")),
        "combined shared secret changed"
    );
    let plaintext =
        decrypt_with_shared_secret(&ciphertext, AAD, &shared_secret)
            .expect("decryption of old ciphertext failed");
    assert_eq!(plaintext, MSG, "decrypted plaintext mismatch");
}
